name: '🚀 Publish'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 🚀 Publish
    runs-on: macos-13
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.4.2
      - name: 🟢 node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: 🧶 Print Yarn Version
        run: yarn --version
      - name: 🚀 Build & Publish
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken "${NODE_AUTH_TOKEN}"
          yarn install
          yarn build
          yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
